### ISSUE TITLE
Feature request amd ad some observations

### ISSUE THREAD

**Issue by G8YTZ** [ea7kir/i2s-PPM-Display#1]
Took me quite a while to work out how to load the software using VS Code as I've not used Platform.IO before, but once done the workflow seems simple. Software loaded ok (I think) as I have a PPM displayed on screen, I just need to connect up the ADC now. Proof will be when I hook up the ADC.

It would be great if the PPM could look like a sound output device when connected to a PC/MAC/Pi via USB and therefore by-passing the need for an ADC. Use case I'm thinking of is a PPM display for received audio on a Ryde receiver, but would also be useful for a PC/Mac too.

An observation, I think it is better to buy the display that has the headers pre-soldered, version 577, for the UK I found the Lilygo store to be easy. I purchased a clone ADC from Ali Express as the official store has a large minimum order value for the UK.

It seems to be working though, just tested with a screwdriver (mains hum) on the input pins. Now tested wit program! Excellent. One thing, the dip switch settings, switch 2 needs to be in the + position (up) - perhaps that's logic zero?

best regards, 

Justin - G8YTZ

**Comment by ea7kir** [comment]
Hi Justin,

I’m really happy to hear you’ve successfully jumped through the VSCODE/PlatformIO hoop.  It took me a long time.

I absolutely agree with your feature request.  To negate the need for an I2S ADC there are options.  One of which would be to find a USB audio to I2S extractor - highly unlikely I know, so I’m hoping someone brighter than I will design one.  Shout about it on the NET and perhaps we’ll get lucky.

Regards,
Michael Naylor - EA7KIR
https://michaelnaylor.es

**Comment by ea7kir** [comment]
It turns out I was wrong.  USB to I2S is all over place - USB Speakers, Headphone,, etc.  Chips and boards.

First examples found on eBay

https://www.ebay.com/sch/i.html?_nkw=Usb%20To%20I2s&norover=1&mkevt=1&mkrid=711-156598-679417-4&mkcid=2&mkscid=102&keyword=usb%20to%20i2s&crlp=435129672851_&MT_ID=585586&geo_id=10232&rlsatarget=kwd-295733265766&adpos=&device=c&mktype=&loc=9048974&poi=&abcId=1141816&cmpgn=6540152590&sitelnk=&adgroupid=80070760458&network=g&matchtype=b&gclid=CjwKCAjw2K6lBhBXEiwA5RjtCbcL1ABgycTu0Aict4Rol-cmgMWmsFTPA5OZ47yWFPC_rY6ips6zfxoCSLgQAvD_BwE <https://www.ebay.com/sch/i.html?_nkw=Usb%20To%20I2s&norover=1&mkevt=1&mkrid=711-156598-679417-4&mkcid=2&mkscid=102&keyword=usb%20to%20i2s&crlp=435129672851_&MT_ID=585586&geo_id=10232&rlsatarget=kwd-295733265766&adpos=&device=c&mktype=&loc=9048974&poi=&abcId=1141816&cmpgn=6540152590&sitelnk=&adgroupid=80070760458&network=g&matchtype=b&gclid=CjwKCAjw2K6lBhBXEiwA5RjtCbcL1ABgycTu0Aict4Rol-cmgMWmsFTPA5OZ47yWFPC_rY6ips6zfxoCSLgQAvD_BwE>

Let me know how you get on.

Regards,
Michael Naylor - EA7KIR
https://michaelnaylor.es

**Comment by G8YTZ** [comment]
Attachments available until 10 Aug 2023
Michael,

I am really delighted with it, I’m going to do some more testing, but also I need to experiment with the HDMI integration. I’ve shared the link on a few FB groups where I think there might be some interest.

Also, how about an Stereo/M-S mode switch, perhaps using another GPIO pin?

I’ve attached a couple of videos.

Justin Cockett
***@***.***
www.gb3jv.co.uk <http://www.gb3jv.co.uk/>
Sent from my MacBook Pro



Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAWLzKbeuIB9q368OQU5eK8mJnjS2AXgYHKg2XwZhoNaiW9lrtPD6MoNU%2F%24%7Bf%7D%3Fo%3DApAGzQA6pyU4gm62s1tHEUjlBTcjd8JJQYgc-Ny15xdj%26v%3D1%26x%3D3%26a%3DCAogu6dbU7OHFIlIlS2fn4cpgDcoqZvBdOoWdCGRWTROhgESdBCNt62QlDEYjceo5J0xIgEAKgkC6AMA_yX-ZPpSBImeNLZaBPoyg1RqJCf7Qm0eY-pC4B-NFcD9NHCY9aulXlXcX2y0XTyoro-Uqu1vrHIkG8rf2B-kgkZFqFHjyAt7S7tJo1pph0XpAH9HJhqQh_YG1twb%26e%3D1691622187%26fl%3D%26r%3D25D79B69-929A-4279-9A59-84D42BA35ECB-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DBAE93A3F-E4D1-4541-B042-3A5C9AC91F49%26p%3D126%26s%3DghMiKnT2nZMSRm4w7Ogej2dZ5JM&uk=zBR-WW4AcbuI3ydR6QWHLQ&f=IMG_6695.MOV&sz=46422523>IMG_6695.MOV
46.4 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAeoa7D3N17DmLvPEREA9qF-sD66DAbO5cq4kVTVKeuIpoxBqDLVmslrV%2F%24%7Bf%7D%3Fo%3DAr2yTyeyY1HebCZzjzbQPGMdQ0Qy9NljuKLKDMnpWPnc%26v%3D1%26x%3D3%26a%3DCAogzLww1GWmMtAVjuMeDzSSSibapG5IE3PhciC3jcLz79MSdBDKuK2QlDEYysio5J0xIgEAKgkC6AMA_33RFX9SBKwProNaBGayWtVqJB-0fHhrwV2XUL-87lLMieo_u0cDPEimij0YmZVHIph_hI1uv3IkZhMrweBePQMU1Hs0iDOu9whURHZxDvPuwhMcWW08pxNAIDhe%26e%3D1691622188%26fl%3D%26r%3D16F4BCD4-A030-4A64-82E9-D3DE2110450C-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DBAE93A3F-E4D1-4541-B042-3A5C9AC91F49%26p%3D126%26s%3D876DWjDkebf3MFe5Xc9O8gEPqi4&uk=kGJa46YxogMSNEougJk-AQ&f=IMG_6698.MOV&sz=73812577>IMG_6698.MOV
73.8 MB

**Comment by G8YTZ** [comment]
I’ll take a look Michael. My mate Mike Shwartz is a BBC Sound guy, we met at Evesham in 1980, but we had mutual friends, he joined in 1979 and is still there! I think he’s going to build one too.

best regards,

Justin Cockett
***@***.***
www.gb3jv.co.uk <http://www.gb3jv.co.uk/>

**Comment by ea7kir** [comment]
This should be fairly simple, except for have to decide which standard to adopt - or just provide both - ie -3db or -6db.

I’ll get around to doing this soon, but I’m currently working on the touchscreen Go versions of q100receiver and q100transmitter.  I remember you were interested in the the Swift Mac versions last year, but I’ve trended to having everything in standalone boxes since then.  However, I do intend to change the repositories of the Swift and Python touchscreen versions to public when I’ve rewritten the readme and install instructions.  As most DATV-ers appear to be in love with Windows, I don’t feel any of this to be a priority.

Regards,
Michael Naylor - EA7KIR
https://michaelnaylor.es

**Comment by G8YTZ** [comment]
Ok! BTW I’ve ordered these from Ali Express, see how I get on…Just found this amazing item on AliExpress. Check it out! ￡7.31  15％ Off | HDMI To I2S Receiver IIS To HDMI Transmit Signal Conversion Board  DAC Decoderhttps://a.aliexpress.com/_EuDCZVvand:Just found this amazing item on AliExpress. Check it out! ￡15.60  32％ Off | STM32 USB To I2S Digital Interface gold plated USB SITIME crystal oscillator 24BIt 96K Compatible Amanero XMOS For HiFi DAC Amphttps://a.aliexpress.com/_EGhYIyjSent from my Remington Rand UNIVACwww.g8ytz.com On 11 Jul 2023, at 07:53, Michael Naylor ***@***.***> wrote:﻿
This should be fairly simple, except for have to decide which standard to adopt - or just provide both - ie -3db or -6db.



I’ll get around to doing this soon, but I’m currently working on the touchscreen Go versions of q100receiver and q100transmitter.  I remember you were interested in the the Swift Mac versions last year, but I’ve trended to having everything in standalone boxes since then.  However, I do intend to change the repositories of the Swift and Python touchscreen versions to public when I’ve rewritten the readme and install instructions.  As most DATV-ers appear to be in love with Windows, I don’t feel any of this to be a priority.



Regards,

Michael Naylor - EA7KIR

https://michaelnaylor.es

**Comment by G8YTZ** [comment]
Hi Michael, today my HDMI to I2S boards arrived, unfortunately no joy, so I am assuming it must be to do with the HDMI signal that I'm feeding it with.

There are no settings on the HDMI - I2S board, but is there a way of tweaking things in the PPM configuration?

This is the board I have, happy to send you one as I have two.

Justin. 

[https://www.aliexpress.com/item/1005003316456642.html?spm=a2g0s.12269583.0.0.7c38530dIy6e68](url)

**Comment by ea7kir** [comment]
They offer 2 boards: HDMI->I2S and I2S->HDMI, so did they send the correct one?  There's little information, but it looks like it should work.  I see it all has SCL and SDA pins - perhaps there's a way to choose between I2S and I2C.

**Comment by G8YTZ** [comment]
They did send two boards and they are both identical in every way...

On the good news side, the USB board I ordered works fine, but having an issue outputting Windows audio to two devices at once.
